services:
  - type: web
    name: multi-org-integration-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://riya037:Riya%40123@cluster0.6bqzn.mongodb.net/multiorg-integration?retryWrites=true&w=majority
      - key: FRONTEND_URL
        value: https://multi-org-integration.vercel.app
      - key: DEMO_MODE
        value: true
      - key: ENABLE_AI_FEATURES
        value: true
      - key: ENABLE_REAL_TIME
        value: true
      - key: LOG_LEVEL
        value: info